### ISSUE TITLE
Look into using scikit-learn's interface to joblib for multiprocessing

### ISSUE THREAD

**Issue by rhiever** [EpistasisLab/scikit-rebate#22]
@weixuanfu2016 is looking into using scikit-learn's interface to joblib for multiprocessing. This may allow scikit-rebate to have multiprocessing on Python 2 as well as Windows.

@weixuanfu2016, please report your findings on this issue.

**Comment by weixuanfu** [comment]
Based on tests so far, joblib from scikit-learn cannot make scikit-rebate have multiprocessing in eithor Python 2 or Windows environment.

The main issue is that the pickle in python 2 do not supported instance method in class (but the pickle in python 3 naively supported instance method). I also tried some workaround mentioned in this [link](http://stackoverflow.com/questions/27318290/why-can-i-pass-an-instance-method-to-multiprocessing-process-but-not-a-multipro). It can make instance method pickleable but joblib only use 1 core instead of multiple cores.

One solution to put multiprocessing in python 2 for scikit-rebate is to put [_get_row_missing](https://github.com/EpistasisLab/scikit-rebate/blob/master/skrebate/relieff.py#L294-L325) and [_compute_scores](https://github.com/EpistasisLab/scikit-rebate/blob/master/skrebate/relieff.py#L361-L366) outside the algorithms class. I make [a branch](https://github.com/weixuanfu2016/scikit-rebate/tree/test_sklearn_joblib) in my forked repo to test the solution in `ReliefF`. It works well in python 2.7. Need more workaround for Windows and other algorithms in rebate.

**Comment by weixuanfu** [comment]
Do you think it is OK for putting these functions out of algorithms class to make them pickleable in python2.7? @rhiever
